image: microsoft/dotnet:latest

stages:
  - build
  - test

before_script:
  - "dotnet restore"

build:
  stage: build
  script:
    - "cd TraceDC"
    - "dotnet build"

test:
  stage: test
  script:
    - "cd xunitTest"
    - "dotnet test"
